services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --save 60 1
      --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
